create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 18),
  avatar text not null default '🧠',
  score integer not null check (score between 0 and 1000000),
  correct integer not null default 0 check (correct >= 0),
  total integer not null default 0 check (total between 1 and 100),
  mode text not null check (mode in ('mixed','four','priority','speed')),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "public can read scores" on public.scores;
create policy "public can read scores"
on public.scores for select
to anon, authenticated
using (true);

drop policy if exists "public can submit scores" on public.scores;
create policy "public can submit scores"
on public.scores for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 18
  and score between 0 and 1000000
  and correct >= 0
  and total between 1 and 100
  and mode in ('mixed','four','priority','speed')
);

create index if not exists scores_score_idx on public.scores(score desc);
create index if not exists scores_mode_score_idx on public.scores(mode, score desc);